# Generated by Django 2.1.4 on 2018-12-09 22:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=255, unique=True)),
                ('descricao', models.TextField(max_length=255)),
                ('conteudo', models.TextField(max_length=255)),
                ('tipo', models.TextField(max_length=255)),
                ('extras', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeVinculada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('rotulo', models.TextField(max_length=255)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=255, unique=True)),
                ('data', models.DateField()),
                ('status', models.TextField(max_length=255)),
                ('plano_ensino', models.TextField(max_length=5000)),
                ('carga_horaria', models.IntegerField()),
                ('competencias', models.TextField(max_length=1000)),
                ('habilidades', models.TextField(max_length=1000)),
                ('ementa', models.TextField(max_length=5000)),
                ('Conteudo_programatico', models.TextField(max_length=5000)),
                ('bibliografia_basica', models.TextField(max_length=1000)),
                ('bibliografia_complementar', models.TextField(max_length=1000)),
                ('percentual_pratico', models.DecimalField(decimal_places=2, max_digits=13)),
                ('percentual_teorico', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio', models.DateField()),
                ('dt_fim', models.DateField()),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('turma', models.TextField(max_length=1)),
                ('metodologia', models.TextField(max_length=255)),
                ('recursos', models.TextField(max_length=255)),
                ('criterio_avaliacao', models.TextField(max_length=1000)),
                ('plano_aula', models.TextField(max_length=1000)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=100)),
                ('resposta', models.TextField(max_length=255)),
                ('dt_entrega', models.DateField()),
                ('status', models.IntegerField()),
                ('nota', models.IntegerField()),
                ('dt_avaliacao', models.DateField()),
                ('obs', models.TextField(max_length=255)),
                ('atividade_vinculada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.AtividadeVinculada')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.TextField(max_length=255)),
                ('referencia', models.TextField(max_length=255)),
                ('conteudo', models.TextField(max_length=255)),
                ('status', models.IntegerField()),
                ('dt_envio', models.DateField()),
                ('dr_resposta', models.DateField()),
                ('resposta', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_solicitacao', models.DateField()),
                ('status', models.TextField(max_length=255)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=255)),
                ('celular', models.TextField(max_length=20)),
                ('dt_expiracao', models.DateField(default=datetime.date(1900, 1, 1))),
                ('login', models.TextField(max_length=20, unique=True)),
                ('senha', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Usuario')),
                ('ra', models.IntegerField()),
                ('foto', models.TextField(max_length=255)),
            ],
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Usuario')),
            ],
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Usuario')),
                ('apelido', models.TextField(max_length=255)),
            ],
            bases=('core.usuario',),
        ),
        migrations.AddField(
            model_name='atividadevinculada',
            name='disciplina_ofertada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.DisciplinaOfertada'),
        ),
        migrations.AddField(
            model_name='solicitacaomatricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Aluno'),
        ),
        migrations.AddField(
            model_name='solicitacaomatricula',
            name='coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Coordenador'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Aluno'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='entregaatividade',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Aluno'),
        ),
        migrations.AddField(
            model_name='entregaatividade',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='disciplinaofertada',
            name='coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Coordenador'),
        ),
        migrations.AddField(
            model_name='disciplinaofertada',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Coordenador'),
        ),
        migrations.AddField(
            model_name='atividadevinculada',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Professor'),
        ),
        migrations.AlterUniqueTogether(
            name='disciplinaofertada',
            unique_together={('curso', 'disciplina', 'turma', 'ano', 'semestre')},
        ),
    ]
